export const PRODUCTS = [
  {
    id: "p1",
    name: "Mango Achar",
    category: "Pickles",
    weight: "250g",
    price: 89,
    wholesalePricePerKg: 320,
    description: "Traditional raw mango pieces pickled with mustard oil, fenugreek, and hand-ground spices.",
    popular: true,
    badge: "Bestseller",
    imageType: "pickle",
    availability: "In Stock (Ready for Bulk Dispatch)",
    ingredients: "Raw Mango, Mustard Oil, Fenugreek, Turmeric, Red Chili Powder, Salt, Asafoetida.",
    storage: "Store in a cool dry place. Use a clean dry spoon.",
    highlights: ["100% Authentic Hyderabad Recipe", "No Artificial Preservatives", "Hand-ground spices in mustard oil"]
  },
  {
    id: "p2",
    name: "Vegetable Achar",
    category: "Pickles",
    weight: "250g",
    price: 89,
    wholesalePricePerKg: 320,
    description: "A delightful assortment of carrots, cauliflower, and green chillies in rich aromatic spices.",
    popular: false,
    badge: "Traditional",
    imageType: "pickle",
    availability: "In Stock (Ready for Bulk Dispatch)",
    ingredients: "Carrots, Cauliflower, Green Chillies, Mustard Seeds, Fennel, Vinegar, Salt, Edible Vegetable Oil.",
    storage: "Keep airtight in a cool dry location.",
    highlights: ["Crunchy Farm Vegetables", "Rich Aromatic Spices", "Prepared under hygienic conditions"]
  },
  {
    id: "p3",
    name: "Lemon Achar",
    category: "Pickles",
    weight: "250g",
    price: 89,
    wholesalePricePerKg: 320,
    description: "Juicy sun-ripened lemons cured to perfection with black salt and roasted cumin.",
    popular: false,
    badge: "Tangy",
    imageType: "pickle",
    availability: "In Stock (Ready for Bulk Dispatch)",
    ingredients: "Sun-ripened Lemons, Black Salt, Cumin, Red Chili Powder, Carom seeds.",
    storage: "Store in a cool dry glass or ceramic container.",
    highlights: ["Digestive & Refreshing", "Sun-cured for optimal flavor", "Zero artificial colors"]
  },
  {
    id: "p4",
    name: "Tomato Achar",
    category: "Pickles",
    weight: "250g",
    price: 89,
    wholesalePricePerKg: 320,
    description: "Rich tangy tomatoes cooked down with garlic, tamarind, and chili powder.",
    popular: false,
    badge: "Special",
    imageType: "pickle",
    availability: "In Stock (Ready for Bulk Dispatch)",
    ingredients: "Ripe Tomatoes, Garlic, Tamarind Pulp, Sesame Oil, Red Chili, Fenugreek, Salt.",
    storage: "Refrigerate after opening for extended freshness.",
    highlights: ["Rich Tangy Flavor", "Perfect companion for rice & tiffins", "Handmade in small batches"]
  },
  {
    id: "p5",
    name: "Fruit Biscuit",
    category: "Biscuits",
    weight: "400g",
    price: 220,
    wholesalePricePerKg: 440,
    description: "Crispy oven-baked biscuits studded with tutti-frutti bits and buttery richness.",
    popular: true,
    badge: "Bakery Fresh",
    imageType: "biscuit",
    availability: "In Stock (Bakery Fresh)",
    ingredients: "Refined Wheat Flour, Butter, Sugar, Tutti-Frutti (Papaya bits), Milk Solids, Baking Powder.",
    storage: "Store in an airtight container to retain crispness.",
    highlights: ["Loaded with Tutti-Frutti", "Melt-in-mouth buttery texture", "Baked fresh daily"]
  },
  {
    id: "p6",
    name: "Cashew Biscuit",
    category: "Biscuits",
    weight: "400g",
    price: 240,
    wholesalePricePerKg: 480,
    description: "Melt-in-the-mouth rich cookies generously loaded with roasted cashew nut pieces.",
    popular: true,
    badge: "Top Rated",
    imageType: "biscuit",
    availability: "In Stock (Bakery Fresh)",
    ingredients: "Refined Wheat Flour, Cashew Nuts, Butter, Sugar, Cardamom Powder, Milk.",
    storage: "Keep sealed in a cool, dry place.",
    highlights: ["Generous Cashew Chunks", "Rich Bakery Butter", "Hyderabad Specialty"]
  },
  {
    id: "p7",
    name: "Osmania Biscuit",
    category: "Biscuits",
    weight: "400g",
    price: 240,
    wholesalePricePerKg: 480,
    description: "The legendary sweet-and-salty buttery biscuit originating from the royal bakers of Hyderabad.",
    popular: true,
    badge: "Hyderabad Special",
    imageType: "biscuit",
    availability: "In Stock (Bakery Fresh)",
    ingredients: "Wheat Flour, Butter, Custard Powder, Salt, Sugar, Milk, Ammonium Bicarbonate.",
    storage: "Store in airtight tin or container.",
    highlights: ["Royal Hyderabad Heritage", "Perfect balance of sweet & salt", "Ideal with hot Irani Chai"]
  },
  {
    id: "p8",
    name: "Pista Biscuit",
    category: "Biscuits",
    weight: "300g",
    price: 270,
    wholesalePricePerKg: 540,
    description: "Delicate shortbread infused with cardamom and topped with crushed green pistachios.",
    popular: false,
    badge: "Royal",
    imageType: "biscuit",
    availability: "In Stock (Bakery Fresh)",
    ingredients: "Wheat Flour, Pistachio Nuts, Butter, Sugar, Cardamom, Saffron Extract.",
    storage: "Store in a cool dry place away from direct sunlight.",
    highlights: ["Topped with Real Pistachios", "Subtle Cardamom Infusion", "Premium Gift Quality"]
  },
  {
    id: "p13",
    name: "Badam Biscuit",
    category: "Biscuits",
    weight: "300g",
    price: 290,
    wholesalePricePerKg: 580,
    description: "Almond-rich buttery baked cookies topped with almond flakes and saffron essence.",
    popular: false,
    badge: "Premium",
    imageType: "biscuit",
    availability: "In Stock (Bakery Fresh)",
    ingredients: "Wheat Flour, Almond Flakes (Badam), Butter, Sugar, Milk, Saffron Essence.",
    storage: "Keep container tightly closed.",
    highlights: ["Rich Almond Flavor", "Topped with crunchy almond flakes", "Baked with pure butter"]
  },
  {
    id: "p14",
    name: "Pure Ghee",
    category: "Ghee & Oils",
    weight: "250g",
    price: 199,
    wholesalePricePerKg: 760,
    description: "100% pure cultured cow ghee with golden granular texture and rich authentic aroma.",
    popular: true,
    badge: "100% Pure",
    imageType: "ghee",
    availability: "In Stock (Ready for Bulk Dispatch)",
    ingredients: "100% Pure Cow Milk Fat (Cultured Ghee).",
    storage: "Store in a cool dry place. Do not refrigerate. Use a dry spoon.",
    highlights: ["Traditional Bilona Method", "Golden Granular Texture", "Rich Authentic Aroma & Taste"]
  }
];

export const BUSINESS_INFO = {
  name: "Taher Ali Enterprises",
  tagline: "Premium Wholesale Food Products",
  description: "Supplying quality products across Hyderabad, Telangana.",
  owner: "Mohammed Abdullah Bilal",
  phone: "6305486808",
  whatsappNumber: "916305486808",
  location: "Hyderabad, Telangana",
  serviceArea: "All over Hyderabad & Telangana",
  businessHours: "Monday - Saturday: 8:00 AM - 8:00 PM (Sunday Open for Bulk Dispatch)",
  established: "1998"
};

export const BULK_TIERS = [
  { minUnits: 1, discountPercent: 0, label: "Retail / Small Pack" },
  { minUnits: 10, discountPercent: 5, label: "Bulk Tier 1 (10+ units: 5% off)" },
  { minUnits: 50, discountPercent: 12, label: "Wholesale Tier 2 (50+ units: 12% off)" },
  { minUnits: 200, discountPercent: 20, label: "Super Stockist Tier (200+ units: 20% off)" }
];
